TRUNCATE TABLE order_item_counts RESTART IDENTITY CASCADE;
TRUNCATE TABLE cart_item_counts RESTART IDENTITY CASCADE;
TRUNCATE TABLE orders RESTART IDENTITY CASCADE;
TRUNCATE TABLE items RESTART IDENTITY CASCADE;
TRUNCATE TABLE images RESTART IDENTITY CASCADE;
